-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 11:52:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Group-Activity-Organizer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Group-Activity-Organizer
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `Group-Activity-Organizer`;
CREATE SCHEMA IF NOT EXISTS `Group-Activity-Organizer` DEFAULT CHARACTER SET utf8 ;
USE `Group-Activity-Organizer` ;

-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`user` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(2048) NOT NULL,
  `userRole` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`activity` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`activity` (
  `activityId` INT NOT NULL AUTO_INCREMENT,
  `activityName` VARCHAR(35) NOT NULL,
  `description` VARCHAR(65) NULL,
  `location` VARCHAR(77) NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `userId` INT NOT NULL,
  `maxParticipant` INT NOT NULL,
  `minParticipant` INT NOT NULL,
  `createBy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`activityId`),
  INDEX `fk_Activities_Users_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Activities_Users`
    FOREIGN KEY (`userId`)
    REFERENCES `Group-Activity-Organizer`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`point`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`points` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`points` (
  `points` INT NOT NULL DEFAULT 1,
  `userId` INT NOT NULL,
  `activityId` INT NOT NULL,
  `activityCompleted` TINYINT NOT NULL DEFAULT 0,
  constraint fk_point_activityId
        foreign key (activityId)
        references activity(activityId),
  CONSTRAINT `fk_Points_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `Group-Activity-Organizer`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`user_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`user_activity` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`user_activity` (
  `userId` INT NOT NULL,
  `activityId` INT NOT NULL,
  PRIMARY KEY (userId, activityId),
  constraint fk_user_activity_activityId
        foreign key (activityId)
        references activity(activityId),
  CONSTRAINT `fk_user_activity_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `Group-Activity-Organizer`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`contact` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`contact` (
  `userId` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `location` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_User Data_Users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_User Data_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `Group-Activity-Organizer`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


delimiter //
create procedure set_known_good_state()
begin  

    delete from contact;	
    delete from points;
    delete from user_activity;
    delete from activity;
    alter table activity auto_increment = 1;    
    delete from user;
    alter table user auto_increment = 1;
      
      
      insert into user(username, password, userRole) values
        ('frigiid', '$2a$10$ntB7CsRKQzuLoKY3rfoAQen5nNyiC/U60wBsWnnYrtQQi8Z3IZzQa', 'admin'),
        ('loneWolf', '$2a$10$ntB7CsRKQzuLoKY3rfoAQen5nNyiC/U60wBsWnnYrtQQi8Z3IZzQa', 'admin'),
        ('guardians', '$2a$10$ntB7CsRKQzuLoKY3rfoAQen5nNyiC/U60wBsWnnYrtQQi8Z3IZzQa', 'admin');
        
	insert into activity(activityName, description, location, date, time, userId, maxParticipant, minParticipant, createBy)
    values
    ('soccer','9v9', 'That one place in Milwaukee','2022-01-11', '15:00', '1', '25', '18', 'Stepfan Thelemaque'),
    ('basketball','5v5', 'Court near Waterfall: Hope, Washington','2022-01-15','05:00', '2', '15','10','John Rambo'),
	('football','5v5, flag football', 'Outer Space','2022-01-23', '12:00', '3', '25','10','Mister Blue Sky'),
    ('soccer','11v11', 'Milwaukee','2022-01-11', '15:00', '1', '25', '18', 'Stepfan Thelemaque'),
    ('basketball','5v5', 'Crypto Arena','2022-02-15','05:00', '2', '15','10','John Rambo'),
	('football','Iron bar tackle football', 'Gridiron Gang','2022-03-23', '12:00', '3', '25','10','Mister Blue Sky'),
    ('Hockey','9v9', 'H-E-Double Hockeysticks','2022-03-11', '15:00', '1', '25', '18', 'Stepfan Thelemaque'),
    ('curling','2v2, contact curling', 'Ice Age Plaza','2022-03-13', '2:00', '3', '6','4','Mister Blue Sky'),
    ('Hockey','9v9', 'Referee is Chad Bloominshine','2022-03-11', '15:00', '1', '25', '18', 'Stepfan Thelemaque'),
     ('basketball','5v5', 'Court near Waterfall: Hope, Washington','2022-04-15','05:00', '2', '15','10','John Rambo'),
	('football','12v5, Unwinnable', 'Outer Space','2022-05-23', '12:00', '3', '25','10','Mister Blue Sky'),
    ('soccer','11v11', 'Kansas City','2022-06-11', '15:00', '1', '25', '5', 'Stepfan Thelemaque'),
    ('football','12v12, touch tackle football', 'Gridiron Gang','2022-06-23', '12:00', '3', '25','10','Mister Blue Sky'),
    ('Hockey','9v9, Go Ducks!', 'If you know you know','2022-08-11', '15:00', '1', '25', '18', 'Stepfan Thelemaque'),
    ('curling','2v2, contact curling', 'Jamaican Bobsled Team','2022-12-13', '2:00', '3', '6','4','Mister Blue Sky'),    
    ('Running','free run', 'Mount Colossus','2023-01-25','06:00', '2', '15','5','John Rambo');
    
    
    insert into contact (userId, firstName, lastName, email, location)
    values 
	('1','Stepfan', 'Thelemaque', null, 'Milwaukee'),
  	('2','John', 'Rambo', null, 'The Forest'),
    ('3','Mister', 'Blue Sky', 'ELO@old.com', 'Sydney');
    
    insert into user_activity
    values
    (1,1),(1,2),(2,2),(3,1),(2,3);
    
    insert into points
    values
    (2,1,1,0),(1,1,2,0),(4,1,3,1);
end //
-- 4. Change the statement terminator back to the original.
delimiter ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;