-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 11:52:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Group-Activity-Organizer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Group-Activity-Organizer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Group-Activity-Organizer` DEFAULT CHARACTER SET utf8 ;
USE `Group-Activity-Organizer` ;

-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`user` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userRole` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`activity` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`activity` (
  `activityId` INT NOT NULL AUTO_INCREMENT,
  `activityName` VARCHAR(35) NOT NULL,
  `description` VARCHAR(65) NULL,
  `location` VARCHAR(77) NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `userId` INT NOT NULL,
  `maxParticipant` INT NOT NULL,
  `minParticipant` INT NOT NULL,
  `createBy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`activityId`),
  INDEX `fk_Activities_Users_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_Activities_Users`
    FOREIGN KEY (`userId`)
    REFERENCES `Group-Activity-Organizer`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`point`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`point` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`point` (
  `points` INT NOT NULL DEFAULT 1,
  `userId` INT NOT NULL,
  `activityCompleted` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_Points_Users1_idx` (`userId` ASC) VISIBLE,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_Points_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `Group-Activity-Organizer`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group-Activity-Organizer`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group-Activity-Organizer`.`contact` ;

CREATE TABLE IF NOT EXISTS `Group-Activity-Organizer`.`contact` (
  `userId` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `location` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_User Data_Users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_User Data_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `Group-Activity-Organizer`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


delimiter //
create procedure set_known_good_state()
begin  

    delete from contact;	
    delete from point;
    delete from activity;
    alter table activity auto_increment = 1;    
    delete from user;
    alter table user auto_increment = 1;
      
      
      insert into user(username, password, userRole) values
        ('frigiid', 'SecretPassword', 'admin'),
        ('loneWolf', 'IStrikeFirst', 'admin'),
        ('guardians', 'OutOfTheBlue', 'admin');
    
    insert into point(userId)
    values
    ('1'),
    ('2'),  
    ('3');   
        
	insert into activity(activityName, description, location, date, time, userId, maxParticipant, minParticipant, createBy)
    values
    ('soccer','9v9', 'That one place in Milwaukee','2022-01-11', '15:00', '1', '25', '18', 'Stepfan Thelemaque'),
    ('basketball','5v5', 'Court beside the waterfall','2022-01-15','05:00', '2', '15','10','John Rambo'),
	('football','5v5, flag football', 'Outer Space','2022-01-23', '12:00', '3', '25','10','Mister Blue Sky');
    
    
    insert into contact (userId, firstName, lastName, email, location)
    values 
	('1','Stepfan', 'Thelemaque', null, 'Milwaukee'),
  	('2','John', 'Rambo', null, 'The Forest'),
    ('3','Mister', 'Blue Sky', 'ELO@old.com', 'Sydney');
    
end //
-- 4. Change the statement terminator back to the original.
delimiter ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
